#!/bin/sh
rm -rf /usr/share/enigma2/GlamourAuraFHD
if [ ! -f /usr/share/enigma2/GlamourAuraBerry/skin.xml ] || [ ! -f /usr/share/enigma2/GlamourAuraLime/skin.xml ] || [ ! -f /usr/share/enigma2/GlamourAuraMango/skin.xml ] || [ ! -f /usr/share/enigma2/GlamourAuraRose/skin.xml ]; then
rm -rf /usr/lib/enigma2/python/Components/Converter/Glam*
rm -rf /usr/lib/enigma2/python/Components/Renderer/Glam*
fi
rm -rf /usr/lib/enigma2/python/Components/Converter/Glam*
rm -rf /usr/lib/enigma2/python/Components/Renderer/Glam*
echo "                                                                     "
echo "Glamour Aura FHD skin was successfully removed from your receiver    "
echo "                                                                     "
echo "The GUI of your receiver is now rebooting....                        "
sleep 5
init 4 && sleep 5 && init 3
