#!/bin/sh
rm -rf /usr/share/enigma2/GlamourAuraFHD 
rm -rf /usr/lib/enigma2/python/Components/Converter/Glam*
rm -rf /usr/lib/enigma2/python/Components/Renderer/Glam*
echo "                                                                      "
echo "Glamour Aura FHD skin was successfully removed from your receiver.    "
echo "Please, restart Enigma2."
