#!/bin/sh
echo "                                                              "
echo "Glamour Aura FHD skin is now being removed from your receiver."
echo "                                                              "
